[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Lidar Lounge Docs"
authors = [{name = "Theo & Alix", email = "theo@ldarlounge.com"}]
dynamic = ["version", "description"]
